### ISSUE TITLE
Chore: setup project structure 

### ISSUE THREAD

**Issue by fredshema** [atlp-rwanda/commanders-medica-backoffice#1]
#### Description

Initialize project structure with next, typescript, tailwind and supabase with project description.

#### Tasks

- [x] Initialize project with nextJs
- [x] Add typescript, tailwind, and supabase with its configuration
- [x] Update Readme file with project description

#### Developer Notes

N/A

#### Related Issues

N/A
