### ISSUE TITLE
Feature: dashboard email auth

### ISSUE THREAD

**Issue by fredshema** [atlp-rwanda/commanders-medica-backoffice#3]
#### Description

Doctors need a way to login and create accounts. A login page and signup page is where these functions will happen.

#### Tasks

- [x] Design login and signup pages
- [x] Design navbar component
- [x] Login and signup implementations 

#### Developer Notes

N/A

#### Related Issues

N/A
