### ISSUE TITLE
Feature: Doctor's dashboard

### ISSUE THREAD

**Issue by justinmihigo** [atlp-rwanda/commanders-medica-backoffice#5]
# Description
After a doctor logs in, he will be redirected to his/her dashboard, this is UI for the doctors that will be like their home  page that shows them the summary of every bit of information but browse to other tabs for more info.

# Tasks
- [ ] Implement the UI as it on figma
- [ ] Make the page responsive on different screens
- [ ] Add interactivity on the buttons where it is needed
# Developer Notes
N/A

# Related Issues
N/A
