### ISSUE TITLE
Feature: Implement Medica web messages

### ISSUE THREAD

**Issue by justinmihigo** [atlp-rwanda/commanders-medica-backoffice#8]
# Description
After a doctor logs in, he or she can be able to view his/ her messages, with the users, he can get the messages related to him, and also be able to reply to them

# Tasks
- [x] Implement the UI as it on figma
- [x] Fetch messages related to the doctor
- [x] Replying to a client
- [x] Making sure to end the session when it is outdated
# Developer Notes
N/A

# Related Issues
N/A
